*DECK AEXCPC
      SUBROUTINE AEXCPC(IDKSGT,LNGTAB,TABSGT,TABLUE)
*
*-----------------------------------------------------------------------
*
* EXTRACTION OF CHARACTER INFORMATION FROM AN INTEGER SEGMENT. COMPONENT
* OF A FORTRAN-77 EMULATOR OF THE SAPHYR ARCHIVE SYSTEM.
*
* INPUT PARAMETERS:
*  IDKSGT : POSITION (IN BYTE) OF INFORMATION IN SEGMENT.
*  LNGTAB : NUMBER OF CHARACTER IN THE INFORMATION.
*  TABSGT : INTEGER SEGMENT.
*
* OUTPUT PARAMETER:
*  TABLUE : CHARACTER*(LNGTAB) INFORMATION.
*
*----------------------------------- AUTHOR: A. HEBERT ; 27/09/1999 ----
*
      INTEGER IDKSGT,LNGTAB,TABSGT(*)
      CHARACTER TABLUE*(*),TEXT4*4
*
      IDK=(IDKSGT+3)/4
      IOF=1
      DO 100 I=1,(LNGTAB+3)/4
        WRITE(TEXT4,'(A4)') TABSGT(IDK+I)
        TABLUE(IOF:IOF+3)=TEXT4
        IOF=IOF+4
  100 CONTINUE
      RETURN
      END
