*DECK AEXGNV
      SUBROUTINE AEXGNV(ICHAMP,SEGMEN,TCHDIM,TCHTYP,TCHDKL,IDK,NV)
*
*-----------------------------------------------------------------------
*
* LOCALIZATION OF A SPECIFIC SEGMENT COMPONENT IN A SAPHYR ARCHIVE.
* COMPONENT OF A FORTRAN-77 EMULATOR OF THE SAPHYR ARCHIVE SYSTEM.
*
* INPUT PARAMETERS:
*  ICHAMP : COMPONENT INDEX IN SEGMENT (LOW INTEGER VALUE).
*  SEGMEN : INTEGER SEGMENT.
*  TCHDIM : DIMENSION OF SEGMENT COMPONENTS.
*  TCHTYP : CHARACTER TYPE OF SEGMENT COMPONENTS.
*  TCHDKL : POSITION OF SEGMENT COMPONENTS.
*
* OUTPUT PARAMETERS:
*  IDK    : POSITION OF SEGMENT COMPONENT WITH INDEX ICHAMP.
*  NV     : LENGTH OF SEGMENT COMPONENT WITH INDEX ICHAMP.
*
*----------------------------------- AUTHOR: A. HEBERT ; 27/09/1999 ----
*
      INTEGER SEGMEN(*),TCHDIM(*),TCHTYP(*),TCHDKL(*)
      CHARACTER TEXT4*4
*
      LONMOT=4
      CALL LCMCAR(TEXT4,.FALSE.,TCHTYP(ICHAMP))
      ND=TCHDIM(ICHAMP)
      IDK=TCHDKL(ICHAMP+1)
      NV=1
      DO 100 ID=1,ND
  100 NV=NV*SEGMEN(IDK+ID)
      IDKE=TCHDKL(ICHAMP)
      IF(IDKE.LT.0) THEN
        IDK=SEGMEN(1-IDKE)+1
      ELSE
        IDK=IDKE+1
      ENDIF
      IF(TEXT4(1:1).EQ.'C') IDK=(IDK-1)/LONMOT+1
      RETURN
      END
